[package]
name = "themis-download"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
env_logger.workspace = true
futures.workspace = true
log.workspace = true
regex.workspace = true
reqwest.workspace = true
reqwest-chain.workspace = true
reqwest-leaky-bucket.workspace = true
reqwest-middleware.workspace = true
reqwest-retry.workspace = true
serde.workspace = true
serde_json.workspace = true
serde-jsonlines.workspace = true
tokio.workspace = true

[lints]
workspace = true
